package it.ispwproject.findyourbook.demo;

import it.ispwproject.findyourbook.model.*;

import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DemoDataStore {
    private static DemoDataStore instance = null;

    private final List<User> users = new ArrayList<>();
    private final List<Book> books = new ArrayList<>();
    private final Map<String, List<Book>> favorites = new HashMap<>();

    private int nextUserId = 10;
    private int nextBookId = 1;
    private static final String DEMO_EMAIL = "auroracicchetta@students.uniroma2.eu";
    private static final java.util.Random RANDOM = new java.util.Random();

    private DemoDataStore() {
        initData();
    }

    public static synchronized DemoDataStore getInstance() {
        if (instance == null) {
            instance = new DemoDataStore();
        }
        return instance;
    }

    public static synchronized void reset() {
        if (instance != null) {
            instance.users.clear();
            instance.books.clear();
            instance.favorites.clear();
            instance.nextUserId = 10;
            instance.nextBookId = 1;
            instance.initData();
        } else {
            instance = new DemoDataStore();
        }
    }

    private void initData() {
        // 1. CARICHIAMO I LETTORI
        users.add(new Reader(1, "Mario", "Rossi", "mario", "DEMO_EMAIL", null, LocalDate.now(java.time.ZoneId.systemDefault()), LocalDate.of(1995, Month.MAY, 20)));

        // 2. CARICHIAMO LE CASE EDITRICI
        users.add(new Publisher(2, "Mondadori", "Editore", "mondadori", "DEMO_EMAIL", null, LocalDate.now(java.time.ZoneId.systemDefault()), "La più grande casa editrice italiana."));
        users.add(new Publisher(3, "Feltrinelli", "Editore", "feltrinelli", "DEMO_EMAIL", null, LocalDate.now(java.time.ZoneId.systemDefault()), "Fondata nel 1954, specializzata in narrativa."));
        users.add(new Publisher(4, "Newton", "Compton", "newton", "DEMO_EMAIL", null, LocalDate.now(java.time.ZoneId.systemDefault()), "Classici a prezzi popolari e gialli."));
        users.add(new Publisher(5, "Einaudi", "Editore", "einaudi", "DEMO_EMAIL", null, LocalDate.now(java.time.ZoneId.systemDefault()), "Punto di riferimento per la cultura e i classici."));

        // ==========================================
        // 3. CATALOGO DEMO
        // ==========================================

        // --- 1. CLASSICI ---
        books.add(createDemoBook("I promessi sposi", "Alessandro Manzoni", "classici", "La monumentale e immortale storia di Renzo e Lucia, due giovani promessi sposi la cui serena felicità viene brutalmente ostacolata dal perfido e prepotente signorotto locale Don Rodrigo. Ambientato nella Lombardia oppressa dalla dominazione spagnola del Seicento, il romanzo si sviluppa attraverso un intricato e drammatico percorso fatto di fughe, separazioni forzate, la paura della calata dei Lanzichenecchi e la spaventosa tragedia della peste manzoniana, fino alla miracolosa e commovente redenzione e ricongiungimento finale.", "https://m.media-amazon.com/images/I/61hsfUlwvzL._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("La Divina Commedia", "Dante Alighieri", "classici", "Il viaggio allegorico, visionario e spirituale del Sommo Poeta Dante Alighieri attraverso i tre regni dell'oltretomba cristiano: l'Inferno, dove assiste alle pene eterne dei dannati e dei grandi personaggi storici; il Purgatorio, luogo di purificazione e speranza; e infine il Paradiso, regno della luce e della beatitudine divina. Guidato prima dal saggio poeta latino Virgilio e poi dall'amata Beatrice, Dante compie un percorso di redenzione universale che ha plasmato per sempre la lingua e la cultura italiana.", "https://m.media-amazon.com/images/I/81FZZ6hw5ML._SL1414_.jpg", "einaudi"));
        books.add(createDemoBook("Delitto e castigo", "Fëdor Dostoevskij", "classici", "Nel soffocante e plumbeo clima di una San Pietroburgo opprimente, il giovane e indigente ex studente Rodion Raskolnikov cova una teoria delirante secondo cui gli uomini straordinari hanno il diritto morale di superare ogni legge per un fine superiore. Spinto dalla miseria e da questa folle idea, compie un efferato duplice omicidio. Da quel momento, tuttavia, non subentra il trionfo, ma un implacabile e devastante crollo psicologico, un duello intellettuale e morale con l'astuto giudice Porfirij e la sofferta via di redenzione attraverso l'amore di Sonja.", "https://m.media-amazon.com/images/I/61n4TPRyZIL._SL1500_.jpg", "newton"));
        books.add(createDemoBook("Il ritratto di Dorian Gray", "Oscar Wilde", "classici", "L'affascinante e corrotto viaggio nell'estetismo e nel peccato di Dorian Gray, un giovane di straordinaria bellezza che, suggestionato dalle teorie ciniche e edoniste di Lord Henry Wotton, esprime un desiderio fatale: che sia il ritratto dipinto da Basil Hallward a invecchiare e a portare i segni del tempo e della depravazione, mentre il suo corpo rimane giovane e incontaminato. Mentre Dorian si abbandona a una vita di segreti abomini e crudeltà, la tela in soffitta si trasforma in un mostruoso e deforme specchio della sua anima.", "https://m.media-amazon.com/images/I/61bRbB4Rk3L._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("Guerra e pace", "Lev Tolstoj", "classici", "Un affresco monumentale e ineguagliabile della Russia imperiale durante il periodo delle devastanti guerre napoleoniche. L'opera intreccia indissolubilmente i destini di grandi figure storiche con le vicende intime, le passioni, i dolori e la crescita spirituale di diverse famiglie aristocratiche, in particolare i Rostov e i Bolkonskij, incarnati dalla tormentata e profonda ricerca di senso della vita da parte di Pierre Bezuchov e del nobile Andrej Bolkonskij.", "https://m.media-amazon.com/images/I/51TCVOVgBPL._SL1000_.jpg", "feltrinelli"));
        books.add(createDemoBook("I miserabili", "Victor Hugo", "classici", "La straordinaria e straziante epopea del riscatto morale e sociale di Jean Valjean, un uomo condannato a diciannove anni di carcere duro per aver rubato un solo pezzo di pane per sfamare i nipoti affamati. Uscito segnato dall'odio ma redento dalla bontà illuminata di un vescovo, Valjean cambia nome e diventa un benefattore e sindaco, ma viene incessantemente braccato dal rigido e inflessibile ispettore di polizia Javert, sullo sfondo di una Francia pervasa da moti rivoluzionari e ingiustizie.", "https://m.media-amazon.com/images/I/61Xm391OIWL._SL1500_.jpg", "newton"));
        books.add(createDemoBook("Moby Dick", "Herman Melville", "classici", "A bordo della baleniera Pequod salpata da Nantucket, il giovane marinaio Ishmael fa i conti con la follia titanica e l'ossessione monomaniacale del comandante, il capitano Ahab. Privato di una gamba da una gigantesca balena bianca, la famigerata Moby Dick, Ahab vive unicamente per la vendetta, trasformando la caccia commerciale in una simbolica e distruttiva crociata contro l'impenetrabile mistero del male e della natura, che coinvolgerà l'intero equipaggio in un epilogo memorabile.", "https://m.media-amazon.com/images/I/713kOZfCINL._SL1500_.jpg", "einaudi"));
        books.add(createDemoBook("Madame Bovary", "Gustave Flaubert", "classici", "La radiografia impietosa e dolorosa del vuoto esistenziale di Emma Bovary, moglie di un bonario medico di campagna, Charles. Lettrice vorace di romanzi rosa e sentimentali, Emma nutre aspettative irrealizzabili nei confronti dell'amore e della passione, finendo ben presto per soffocare nella noia opprimente della vita di provincia. Nel tentativo di dare colore alla propria esistenza, si lancia in relazioni extraconiugali sconsiderate e in una spirale di debiti finanziari con l'odioso mercante Lheureux, che la condurranno alla catastrofe.", "https://m.media-amazon.com/images/I/61d1KFQ3d-L._SL1500_.jpg", "feltrinelli"));
        books.add(createDemoBook("Anna Karenina", "Lev Tolstoj", "classici", "La travolgente, scandalosa e distruttiva passione d'amore che divampa tra la aristocratica e affascinante Anna Karenina e il brillante ufficiale conte Aleksej Vronskij nella San Pietroburgo di fine Ottocento. Il legame costa ad Anna l'isolamento sociale, l'allontanamento dall'amato figlio e il giudizio impietoso del mondo perbenista, un dramma interiore che si specchia e si contrappone alla limpida e faticosa ricerca di armonia familiare e spirituale vissuta dal proprietario terriero Levin.", "https://m.media-amazon.com/images/I/71ab2xrxhxL._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("Il fu Mattia Pascal", "Luigi Pirandello", "classici", "La tragicomica e paradossale avventura di Mattia Pascal, bibliotecario in un paese ligure soffocato da un matrimonio infernale e da una suocera tiranna. In seguito a una vincita inaspettata al casinò di Montecarlo, Mattia legge sul giornale che un cadavere sfigurato è stato identificato come il suo. Invece di smentire, coglie l'occasione per liberarsi della sua identità passata e viaggia con un nuovo nome, Adriano Meis. Ma scoprirà ben presto che la libertà assoluta, senza uno stato civile e un'identità legale riconosciuta, è una prigione ben peggiore della precedente.", "https://m.media-amazon.com/images/I/61DhxRWMNvL._SL1231_.jpg", "einaudi"));
        books.add(createDemoBook("Frankenstein", "Mary Shelley", "classici", "La cupa, tragica e visionaria storia del giovane e ambizioso scienziato Victor Frankenstein, il quale, ossessionato dal desiderio di sconfiggere la morte e svelare i segreti della scintilla vitale, riesce a infondere la vita in una creatura assemblata con parti di cadaveri sottratti alle tombe. Inorridito dal risultato mostruoso del suo esperimento, Victor fugge abbandonando il 'demone' a se stesso. Reietto dalla società, incompreso e sopraffatto dalla solitudine e dal dolore, l'essere mostruoso intraprende un cammino di vendetta spietata contro il suo creatore, in un drammatico confronto sui limiti etici della scienza e sulla natura dell'umanità.", "https://m.media-amazon.com/images/I/81ssmAQSiRL._SL1500_.jpg", "newton"));
        books.add(createDemoBook("Il Decameron", "Giovanni Boccaccio", "classici", "La monumentale raccolta di cento novelle incorniciate dal celebre 'lieto convito' di un gruppo di sette ragazze e tre giovani fiorentini i quali, per sfuggire alla spaventosa peste nera che flagella Firenze nel 1348, si rifugiano in una splendida villa in campagna. Per trascorrere le giornate in letizia, i giovani eleggono a turno un re o una regina della brigata e si raccontano storie incentrate sull'ingegno umano, sulle beffe, sulla fortuna e sulla multiforme potenza dell'amore in tutte le sue sfumature, inaugurando la grande prosa in volgare della letteratura italiana.", "https://m.media-amazon.com/images/I/711hxR4oJyL._SL1500_.jpg", "einaudi"));

        // --- 2. FANTASY ---
        books.add(createDemoBook("Il Signore degli Anelli", "J.R.R. Tolkien", "fantasy", "L'epico e insuperabile viaggio della Compagnia dell'Anello, formata da uomini, un elfo, un nano, hobbit e lo stregone Gandalf, determinati a percorrere la Terra di Mezzo fino alle terre oscure di Mordor per distruggere l'Unico Anello nel fuoco del Monte Fato e sconfiggere per sempre il potere dell'Oscuro Signore Sauron, in un racconto fondativo della letteratura fantastica moderna.", "https://m.media-amazon.com/images/I/6190PaQZkrL._SL1500_.jpg", "einaudi"));
        books.add(createDemoBook("Le cronache di Narnia", "C.S. Lewis", "fantasy", "Quattro fratelli – Peter, Susan, Edmund e Lucy – scoprono che un vecchio armadio è in realtà un portale magico. Oltre le ante di legno si nasconde Narnia, un mondo incantato popolato da animali parlanti e congelato in un inverno senza fine dalla malvagia Strega Bianca. Guidati dal maestoso leone Aslan, i ragazzi dovranno affrontare epiche battaglie, creature mitologiche e tradimenti per spezzare l'oscura maledizione e riportare la primavera nel regno.", "https://m.media-amazon.com/images/I/71+eLNG0bXL._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("Il Trono di Spade", "George R.R. Martin", "fantasy", "Gli intrighi spietati, le lotte di potere, i duelli e i tradimenti sanguinosi tra le nobili casate del continente di Westeros, dai ghiacci del Nord al caldo sud, tutti in lizza per il controllo del famigerato Trono di Spade. Mentre le famiglie si dilaniano a vicenda con alleanze fragili e vendette implacabili, alle frontiere estreme del regno, oltre la grande Barriera di ghiaccio, si risvegliano minacce antiche e dimenticate.", "https://m.media-amazon.com/images/I/71I7798hdLL._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("Una corte di rose e spine", "Sarah J. Maas", "fantasy", "Quando la diciannovenne Feyre uccide un lupo nella foresta per sopravvivere al gelido inverno, una creatura spaventosa si presenta alla sua porta per reclamare vendetta. Trascinata nel magico e letale regno di Prythian, scoprirà che il suo rapitore, Tamlin, non è un mostro, ma uno dei potenti Fae maggiori. Tra i due nascerà un legame inaspettato, mentre un'antica ombra oscura minaccia di distruggere il loro mondo.", "https://m.media-amazon.com/images/I/515-5j7sFhL._SY445_SX342_ML2_.jpg", "mondadori"));
        books.add(createDemoBook("American Gods", "Neil Gaiman", "fantasy", "Shadow Moon, un ex detenuto che ha appena scontato la sua pena, viene scosso dalla morte improvvisa della moglie e si ritrova arruolato come guardia del corpo dal misterioso e carismatico signor Wednesday. Inizia così un viaggio onnipresente e allucinato attraverso le autostrade americane, scoprendo che è in corso una furiosa guerra sotterranea tra le vecchie divinità mitologiche sbiadite e i nuovi arroganti dèi della modernità e della tecnologia.", "https://m.media-amazon.com/images/I/7146xxh252L._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("Il cuore della regina", "Nisha J. Tuli", "fantasy", "Lor ha trascorso gli ultimi dodici anni come prigioniera di Nostraza, sopportando la crudeltà del Re di Aurora. Quando un'inaspettata rivolta le permette di fuggire, si ritrova magicamente trasportata alla corte del Re del Sole, dove è costretta a partecipare a sfide mortali contro altre ragazze per conquistare il cuore del sovrano e il titolo di Regina.", "https://m.media-amazon.com/images/I/91INnUFAnaL._SY522_.jpg", "newton"));
        books.add(createDemoBook("Elianto", "Stefano Benni", "fantasy", "In un mondo parallelo governato da tiranni corrotti e bizzarri, il giovane Elianto è colpito da una malattia misteriosa. Per salvarlo, un gruppo di strampalati amici dovrà viaggiare attraverso contee magiche, affrontando diavoli, divinità televisive e burocrati infernali in un'epica e geniale satira fantasy.", "https://m.media-amazon.com/images/I/71kCfG0qWhL._SL1205_.jpg", "feltrinelli"));
        books.add(createDemoBook("Il priorato dell'albero delle arance", "Samantha Shannon", "fantasy", "Un epico e maestoso racconto di draghi, regine e magia. Il regno di Inys è minacciato dal risveglio di un drago leggendario, e l'unica speranza risiede in un'alleanza impossibile tra nazioni divise, segreti millenari e l'ordine segreto del Priorato che protegge la magia.", "https://m.media-amazon.com/images/I/81-DAHZFNpL._SY522_.jpg", "mondadori"));
        books.add(createDemoBook("Nevernight - Mai dimenticare", "Jay Kristoff", "fantasy", "In un mondo dove i tre soli non tramontano quasi mai, la sedicenne Mia Corvere si unisce alla Chiesa Rossa, una spietata e letale accademia di assassini. Il suo unico scopo è vendicarsi dei potenti che hanno distrutto la sua famiglia. Tra compagni spietati, prove mortali e un oscuro potere che le permette di manipolare le ombre, Mia dovrà diventare l'arma più affilata della Repubblica.", "https://m.media-amazon.com/images/I/81zMxGB3gaL._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("La città di ottone", "S.A. Chakraborty", "fantasy", "Nahri non crede nella magia, ma sopravvive per le strade del Cairo truffando nobili con false letture del futuro. Finché, durante un finto rituale, evoca per sbaglio Dara, un antico e letale guerriero djinn. Braccata da creature mostruose, Nahri fuggirà con lui verso Daevabad, la leggendaria Città di Ottone, un luogo di intrighi di corte e faide millenarie in cui il suo sangue avrà un peso inestimabile.", "https://m.media-amazon.com/images/I/81MfDfznxBL._SY522_.jpg", "mondadori"));
        books.add(createDemoBook("Il ladro di fulmini", "Rick Riordan", "fantasy", "Percy Jackson ha dodici anni, è dislessico e ha un talento naturale per cacciarsi sempre nei guai. La sua vita viene stravolta quando scopre una verità incredibile: gli antichi dei greci esistono ancora e lui è un semidio, figlio di Poseidone. Accusato di aver rubato la Folgore di Zeus, Percy dovrà intraprendere un viaggio epico e pericolosissimo per ritrovarla e sventare una guerra sull'Olimpo.", "https://m.media-amazon.com/images/I/71NF1aeC-xL._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("Harry Potter e la Pietra Filosofale", "J.K. Rowling", "fantasy", "Un giovane e bistrattato orfano, costretto a vivere nel sottoscala degli zii babbani, scopre improvvisamente in preda alla magia di essere un mago famoso. Viene così introdotto da Mezzogiorno nei segreti del binario nove e tre quarti, facendo il suo sfolgorante ingresso nel castello di Hogwarts, una scuola di magia e stregoneria celata al mondo, dove affronterà amicizie indissolubili e le prime ombre del ritorno di Voldemort.", "https://m.media-amazon.com/images/I/71CvZU5-quL._SL1479_.jpg", "mondadori"));

        // --- 3. ROMANCE ---
        books.add(createDemoBook("Orgoglio e pregiudizio", "Jane Austen", "romance", "Nell'Inghilterra rurale dell'Ottocento, la brillante e ostinata Elizabeth Bennet si scontra costantemente con il ricco, altero e riservato signor Darcy. Tra eleganti balli di campagna, pettegolezzi di provincia e le rigide convenzioni sociali dell'epoca, i due dovranno superare il proprio orgoglio e i reciproci malintesi. Solo spogliandosi dei loro pregiudizi riusciranno a riconoscere la profonda affinità intellettuale e la passione autentica che li lega inesorabilmente.", "https://m.media-amazon.com/images/I/71AET+iM0oL._SL1500_.jpg", "feltrinelli"));
        books.add(createDemoBook("Cime tempestose", "Emily Brontë", "romance", "Nelle selvagge e desolate brughiere dello Yorkshire, si consuma la passione distruttiva, assoluta e crudele tra lo scontroso trovatello Heathcliff e la ribelle Catherine Earnshaw. Il loro legame, tanto profondo da sfidare le convenzioni borghesi, la morale, il tempo e persino la morte, si trasformerà in una maledizione implacabile. Un sentimento divorante che finirà per travolgere non solo le loro esistenze, ma anche quelle delle generazioni future in un vortice di vendetta e follia.", "https://m.media-amazon.com/images/I/61qfetCDhHL._SL1500_.jpg", "feltrinelli"));
        books.add(createDemoBook("Jane Eyre", "Charlotte Brontë", "romance", "Rimasta orfana e cresciuta in un ambiente freddo e ostile, la giovane e volitiva Jane Eyre trova lavoro come istitutrice nell'isolata e gotica tenuta di Thornfield Hall. Qui incontra l'enigmatico e tormentato padrone di casa, il signor Rochester, verso il quale inizia a nutrire un amore profondo, paritario e totalmente ricambiato. Ma proprio a un passo dalla felicità, un oscuro e terribile segreto nascosto nel passato dell'uomo la costringerà a mettere alla prova tutta la sua indipendenza e forza morale.", "https://m.media-amazon.com/images/I/71Oy6VUOCNL._SL1500_.jpg", "feltrinelli"));
        books.add(createDemoBook("Ragione e sentimento", "Jane Austen", "romance", "Le sorelle Dashwood, Elinor e Marianne, rappresentano due modi diametralmente opposti di affrontare la vita e l'amore: la prima è guidata dalla razionalità e dal decoro, la seconda si abbandona totalmente agli impulsi del cuore e alla passione romantica. Rimaste improvvisamente senza mezzi dopo la morte del padre, dovranno navigare tra cocenti delusioni amorose, pretendenti inaffidabili e ipocrisie sociali. Entrambe scopriranno a proprie spese che per conquistare la vera felicità serve un delicato equilibrio tra le ragioni dell'intelletto e le urgenze dell'anima.", "https://m.media-amazon.com/images/I/81RTwp8btnL._SL1500_.jpg", "feltrinelli"));
        books.add(createDemoBook("Due cuori in affitto", "Felicia Kingsley", "romance", "Summer e Blake sono due persone diametralmente opposte che, a causa di un equivoco burocratico, si ritrovano a dover condividere la stessa casa vacanze negli Hamptons per l'intera estate. Lei è una sceneggiatrice romantica e meticolosa alla ricerca dell'ispirazione perduta, lui un romanziere cinico, caotico e sciupafemmine che non crede affatto nel vero amore. Tra battibecchi esilaranti, regole di convivenza infrante e una chimica esplosiva impossibile da ignorare, i due scopriranno che gli opposti non solo si attraggono, ma rischiano di innamorarsi perdutamente.", "https://m.media-amazon.com/images/I/51PIZoniRYL._SL1000_.jpg", "newton"));
        books.add(createDemoBook("Ti prego lasciati odiare", "Anna Premoli", "romance", "Jennifer e Ian lavorano nella stessa banca d'affari londinese e si detestano cordialmente fin dal primo giorno, scambiandosi battute al vetriolo e sfide professionali all'ultimo sangue. Quando, per evitare uno scandalo finanziario, sono costretti dai loro superiori a fingere una relazione felice e collaborare a un progetto importante, le loro certezze iniziano a vacillare. Sotto la maschera dell'ostilità, scopriranno una complicità inaspettata e una passione travolgente che metterà in discussione tutte le loro rigide regole di vita.", "https://m.media-amazon.com/images/I/81TlROntgJL._SL1500_.jpg", "newton"));
        books.add(createDemoBook("Il contratto", "Elle Kennedy", "romance", "Hannah ha una cotta disperata per il ragazzo d'oro del college, ma non sa come attirare la sua attenzione, essendo estremamente insicura. Garrett, la stella della squadra di hockey, rischia di perdere la borsa di studio a causa di un pessimo voto in etica ed è disposto a tutto pur di superare l'esame. I due stringono un patto segreto: lei gli darà ripetizioni per passare il corso, e in cambio lui fingerà di uscire con lei per far ingelosire il ragazzo che le piace, trasformando presto la finzione in una realtà troppo intensa per essere ignorata.", "https://m.media-amazon.com/images/I/81UrDwkiMxL._SL1500_.jpg", "newton"));
        books.add(createDemoBook("Facciamo finta che mi ami", "Elena Armas", "romance", "Catalina Martín ha un disperato bisogno di un accompagnatore per il matrimonio di sua sorella in Spagna, per non presentarsi da sola davanti alla sua caotica famiglia e, soprattutto, al suo ex fidanzato. Quando Aaron Blackford, il suo affascinante, arrogante e insopportabile collega, si offre volontario per farle da finto fidanzato, Catalina vorrebbe rifiutare a tutti i costi, ma non ha alternative. Tra un volo transatlantico, presentazioni ufficiali e imbarazzanti situazioni di finta intimità, i due dovranno fingere di essere follemente innamorati davanti a tutti. Tuttavia, sotto il caldo sole spagnolo, il confine tra la rigida finzione lavorativa e un sentimento reale e travolgente inizierà inesorabilmente a sfocare.", "https://m.media-amazon.com/images/I/71De2OivHlL._SL1500_.jpg", "newton"));
        books.add(createDemoBook("Rosso, bianco & sangue blu", "Casey McQuiston", "romance", "Alex Claremont-Diaz, il carismatico figlio della Presidente degli Stati Uniti, si ritrova costretto a gestire una finta amicizia di facciata con il principe Henry d'Inghilterra in seguito a un teso incidente diplomatico che ha coinvolto una torta nuziale. Quello che inizia come un rapporto di fredda antipatia e ripicche si trasforma ben presto in un flirt segreto, appassionato e travolgente. La loro relazione clandestina, fatta di messaggi notturni e fughe romantiche, rischierà di sconvolgere i rigidi equilibri della politica internazionale.", "https://m.media-amazon.com/images/I/61pghBQ-+bL._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("Io prima di te", "Jojo Moyes", "romance", "Louisa Clark è una ragazza eccentrica, solare e priva di grandi ambizioni che accetta un lavoro come assistente di Will Traynor, un brillante giovane banchiere la cui vita avventurosa è stata distrutta da un incidente che lo ha reso tetraplegico. Inizialmente scontroso e desideroso di farla finita, Will troverà nella tenacia e nei colori sgargianti di Lou una ventata di imprevedibile allegria. Insieme intraprenderanno un percorso emotivo devastante e dolcissimo, che cambierà profondamente le prospettive di entrambi.", "https://m.media-amazon.com/images/I/61leM4XOrSL._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("Bridgerton: Il Duca e io", "Julia Quinn", "romance", "Nella sfarzosa e pettegola Londra dell'Età della Reggenza, la brillante Daphne Bridgerton debutta in società con l'obiettivo di trovare un marito, ma i corteggiatori scarseggiano a causa dei fratelli iperprotettivi. Il Duca di Hastings, scapolo impenitente, le propone un finto corteggiamento per allontanare le madri ambiziose e far apparire Daphne desiderabile. Un piano geniale, se non fosse per le scintille e la passione reale che iniziano inesorabilmente a divampare tra loro a ogni ballo della stagione.", "https://m.media-amazon.com/images/I/61d1HexQ8LL._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("I Love Shopping", "Sophie Kinsella", "romance", "Rebecca Bloomwood è una giornalista londinese dal cuore d'oro, che ironicamente dispensa consigli su come gestire i risparmi ma è affetta da un'irrefrenabile compulsione per lo shopping, trovandosi sommersa dai debiti. La sua vita caotica prende una piega inaspettata quando incrocia la strada di Luke Brandon, un affascinante, milionario e rigoroso genio della finanza. Tra disastri comici, segreti svelati e vetrine scintillanti, nascerà una storia d'amore frizzante che le insegnerà il vero valore delle cose.", "https://m.media-amazon.com/images/I/61l+HbitwQL._SL1500_.jpg", "mondadori"));

        // --- 4. GIALLI ---
        books.add(createDemoBook("Dieci piccoli indiani", "Agatha Christie", "gialli", "Dieci persone apparentemente senza alcun legame comune tra loro vengono misteriosamente invitate su una isolata e cupa roccia al largo della costa del Devon da un anfitrione che si fa chiamare signor U.N. Owen. Una volta giunti nella magnifica villa, un grammofono accusa ciascuno di loro di aver commesso in passato un omicidio rimasto impunito. Isolati dal maltempo e senza via di fuga, gli ospiti iniziano a essere eliminati uno alla volta, seguendo spietatamente i versi di una vecchia e macabra filastrocca infantile incisa in ogni camera, mentre il panico e il sospetto reciproco distruggono ogni briciolo di lucidità.", "https://m.media-amazon.com/images/I/711jiyCoP+L._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("Assassinio sull'Orient Express", "Agatha Christie", "gialli", "Durante un lussuoso e affollato viaggio sull'Orient Express, il leggendario treno viene improvvisamente bloccato da una fitta e impenetrabile nevicata nel bel mezzo dei Balcani. Nel cuore della notte, un odioso e spregiudicato uomo d'affari americano viene brutalmente assassinato nel suo scompartimento con ben dodici coltellate. Poiché il treno è bloccato e non ci sono vie d'accesso esterne, l'assassino si nasconde inevitabilmente tra i passeggeri dell'vagone. Spetta al celebre e meticoloso investigatore belga Hercule Poirot, aiutato dalla sua ineguagliabile materia grigia, esaminare indizi contrastanti, false identità e alibi apparentemente di ferro per svelare una verità sbalorditiva e profondamente tragica.", "https://m.media-amazon.com/images/I/71-gfpil2WL._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("Il mastino dei Baskerville", "Arthur Conan Doyle", "gialli", "Il leggendario e acuto detective Sherlock Holmes e il suo fido compagno dottor Watson vengono ingaggiati per risolvere un mistero antico e spettrale che minaccia la nobile e aristocratica famiglia dei Baskerville. Nelle desolate, nebrosose e infide lande del Dartmoor si aggirerebbe una creatura mostruosa e diabolica, un mastino spettrale dagli occhi di fuoco deciso a vendicare un'antica maledizione di famiglia. Tra torbiere infide, ululati agghiaccianti nella notte e una fitta rete di inganni umani, Holmes dovrà separare la superstizione popolare dalla fredda e calcolata realtà criminale per catturare il vero colpevole appostato nell'ombra.", "https://m.media-amazon.com/images/I/51Av9TA3aNL._SY445_SX342_QL70_ML2_.jpg", "newton"));
        books.add(createDemoBook("La donna nel pozzo", "Piergiorgio Pulixi", "gialli", "Un intenso, stratificato e teso thriller poliziesco italiano che scava nei traumi inconfessati, nelle colpe sommerse e nelle torbide zone d'ombra della provincia sarda e del tessuto metropolitano. Quando il corpo di una donna viene rinvenuto in fondo a un vecchio pozzo rurale, le indagini di una squadra investigativa tormentata da demoni personali si scontrano con un muro di omertà, silenzi e depistaggi. Un'indagine che parte come un classico caso di cronaca nera e si evolve rapidamente in un viaggio doloroso e spietato dentro le dinamiche perverse del potere locale e della memoria collettiva.", "https://m.media-amazon.com/images/I/71uvEXrGCEL._SL1500_.jpg", "feltrinelli"));
        books.add(createDemoBook("Il tempo dell'orologiaio", "Maurizio de Giovanni", "gialli", "Un'indagine suggestiva, malinconica e intrisa di straordinaria umanità tra i vicoli stretti, affollati e risonanti di una Napoli d'altri tempi, sospesa tra miseria e splendore. Il commissario Ricciardi, dotato della tragica e dolorosa capacità di percepire le ultime parole pronunciate dai morti a causa di una morte violenta, si trova a fronteggiare un delitto apparentemente inspiegabile nel mondo degli artigiani. Tra passioni soffocate, segreti di quartiere, il profumo del caffè e il peso opprimente di un dono soprannaturale che consuma l'anima, Ricciardi dipana una matassa di sentimenti estremi e verità nascoste.", "https://m.media-amazon.com/images/I/81vvUI2t6tL._SL1500_.jpg", "feltrinelli"));
        books.add(createDemoBook("Il socio", "John Grisham", "gialli", "Un giovane, ambizioso e brillante laureato in legge di Harvard entra a far parte, con l'offerta della vita, di un piccolo ma misteriosamente ricchissimo studio legale di Memphis. Ben presto, però, l'illusione del successo svanisce: il protagonista scopre che l'azienda è saldamente controllata e manovrata dalla mafia, i suoi soci muoiono in circostanze sospette e l'FBI lo torchia pretendendo la collaborazione totale in un gioco al massacro senza esclusione di colpi, dove la sua stessa sopravvivenza dipenderà da un bluff disperato.", "https://m.media-amazon.com/images/I/81pT71OHqIL._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("L'enigma dell'abate nero", "Marcello Simoni", "gialli", "Un grande e meticoloso thriller storico ambientato nel Quattrocento fiorentino. Il banchiere Giannotto Bruni viene trovato brutalmente ucciso nella cripta dell'abbazia di Santa Trìnita. L'unico testimone oculare del crimine risulta essere un giovane ladro di origini oscure di nome Tigrinus, il quale si ritroverà braccato e costretto a stringere un patto disperato con la potente famiglia de' Medici pur di svelare la verità.", "https://m.media-amazon.com/images/I/81q-g1Pfr7L._SL1500_.jpg", "newton"));
        books.add(createDemoBook("La maledizione del corvo nero", "Ann Cleeves", "gialli", "In una fredda e gelida mattina di gennaio, le isole Shetland sono completamente sepolte da una spessa coltre di neve candida. Mentre una donna rincasa, il suo sguardo viene catturato da uno sprazzo di colore scuro sul terreno e da stormi di corvi neri che volteggiano minacciosi. Lì in mezzo giace il cadavere di una giovane vicina di casa. Un'indagine psicologica profonda e claustrofobica che getterà nel panico un'intera comunità insulare.", "https://m.media-amazon.com/images/I/81aFJcmIrZL._SL1500_.jpg", "newton"));
        books.add(createDemoBook("L'assassinio di Roger Ackroyd", "Agatha Christie", "gialli", "Nel tranquillo villaggio di King's Abbott, il ricco vedovo Roger Ackroyd viene trovato assassinato nello studio della sua villa di Fernly Park, pugnalato alle spalle con un pugnale tunisino di grande valore. Il delitto arriva a pochissimi giorni di distanza dalla misteriosa morte per overdose della donna che Ackroyd amava e che era ricattata da un misterioso estorsore. A indagare sull'enigma si trova l'investigatore belga Hercule Poirot, ritiratosi nel villaggio per coltivare zucche. Coadiuvato dal dottor James Sheppard, che funge da voce narrante e assistente, Poirot scaverà tra i segreti di famiglia, i debiti nascosti, i servitori infedeli e i ricatti incrociati della residenza, smascherando il colpevole attraverso un finale geniale e tra i più rivoluzionari e discussi nella storia della letteratura gialla mondiale.", "https://m.media-amazon.com/images/I/717NEcHWElL._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("L'uomo di neve", "Jo Nesbø", "gialli", "Dopo la prima neve dell'anno, il piccolo Jonas si sveglia e scopre che la madre è scomparsa: la sua sciarpa è avvolta al collo di un pupazzo di neve apparso misteriosamente in giardino. Quando una seconda donna sparisce nei dintorni di Oslo, l'ispettore Harry Hole capisce di trovarsi di fronte al primo serial killer nella storia della Norvegia. Una caccia all'uomo che lo condurrà nei recessi più oscuri della mente umana.", "https://m.media-amazon.com/images/I/618Y2BID7hL._SL1500_.jpg", "einaudi"));
        books.add(createDemoBook("Il senso del dolore", "Maurizio de Giovanni", "gialli", "Napoli, anni Trenta: il celebre tenore Arnaldo Vezzi, convinto della propria intoccabilità, viene trovato assassinato nel suo camerino poco prima di uno spettacolo. Il commissario Ricciardi, capace di percepire gli spettri delle vittime e le loro ultime parole, dovrà muoversi tra superstizione, potere e gelosie per svelare la verità. Il romanzo che apre la saga delle stagioni del commissario più enigmatico della narrativa italiana.", "https://m.media-amazon.com/images/I/71HiNwZQDGL._SL1385_.jpg", "einaudi"));
        books.add(createDemoBook("Il codice da Vinci", "Dan Brown", "gialli", "Un omicidio all'interno del Museo del Louvre trascina il symbologista Robert Langford e la crittologa Sophie Neveu in una corsa rocambolesca tra Parigi e Londra. Seguendo una scia di indizi nascosti nelle opere di Leonardo da Vinci, i due scoprono un segreto religioso millenario custodito da una società segreta, braccati da un implacabile sicario dell'Opus Dei.", "https://m.media-amazon.com/images/I/71WlWEKzX8L._SL1500_.jpg", "mondadori"));


        // --- 5. AVVENTURA ---
        books.add(createDemoBook("Sandokan", "Emilio Salgari", "avventura", "Sull'isola inespugnabile di Mompracem vive Sandokan, la Tigre della Malesia, principe spodestato dagli inglesi che gli hanno sterminato la famiglia. Circondato dai suoi fedeli tigrotti e affiancato dall'inseparabile Yanez, si getta in una vita fatta di arrembaggi e battaglie, finché una ferita lo porta sulle coste di Labuan, dove incontra la bellissima Marianna. Da quel momento sarà disposto a rischiare tutto pur di farla sua regina.", "https://m.media-amazon.com/images/I/716zPhFO8cL._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("Tutti i particolari in cronaca", "Antonio Manzini", "avventura", "Walter Andretti è un giornalista precipitato dallo sport alla cronaca nera, l'ultimo posto dove avrebbe voluto lavorare. Quando il suo capo gli affida la copertura di due omicidi apparentemente slegati, Andretti si ritrova suo malgrado a indagare, inciampando in goffaggini e passi falsi. Ma dietro quelle morti si cela un legame inquietante, una stessa mano che nessuno aveva saputo vedere, e che lo costringerà a mettere in gioco più di quanto avrebbe voluto.", "https://m.media-amazon.com/images/I/71+yJKKElRL._SL1359_.jpg", "mondadori"));
        books.add(createDemoBook("Il Corsaro Nero", "Emilio Salgari", "avventura", "Scuro e spietato, il Corsaro Nero solca i Mari dei Caraibi in cerca di vendetta contro il duca fiammingo che ha tradito e ucciso i suoi fratelli. Tra abbordaggi, foreste vergini e duelli furiosi, il temuto filibustiere si scontra con il proprio destino quando incontra la bella Honorata, costringendolo a scegliere tra l'odio che lo consuma e un amore inatteso e travolgente.", "https://m.media-amazon.com/images/I/71KoPPOlv2L._SL1328_.jpg", "mondadori"));
        books.add(createDemoBook("Ventimila leghe sotto i mari", "Jules Verne", "avventura", "Un misterioso mostro marino semina il panico negli oceani di tutto il mondo, finché la nave Abraham Lincoln non parte alla sua caccia. Il professor Aronnax e i suoi compagni scoprono che il mostro è in realtà il Nautilus, uno straordinario sottomarino guidato dall'enigmatico capitano Nemo. Un viaggio mozzafiato tra abissi sconosciuti, creature mai viste e i segreti di un uomo che ha scelto di fuggire dal mondo degli uomini.", "https://m.media-amazon.com/images/I/71KNTamCujL._SL1500_.jpg", "feltrinelli"));
        books.add(createDemoBook("Il giro del mondo in ottanta giorni", "Jules Verne", "avventura", "Il flemmatico gentiluomo inglese Phileas Fogg scommette l'intera sua fortuna di poter circumnavigare il globo in appena ottanta giorni. Insieme al fedele domestico Passepartout, affronta treni, piroscafi ed elefanti, in una corsa contro il tempo tra imprevisti, inseguimenti e un ispettore di Scotland Yard convinto che Fogg sia un pericoloso ladro in fuga.", "https://m.media-amazon.com/images/I/61SLqGXWKxL._SL1500_.jpg", "feltrinelli"));
        books.add(createDemoBook("L'isola del tesoro", "Robert Louis Stevenson", "avventura", "Il giovane Jim Hawkins trova per caso la mappa di un tesoro nascosto appartenuto a un vecchio pirata, e si imbarca su una goletta diretta verso un'isola remota. Ma tra l'equipaggio si nasconde il temibile Long John Silver, capace di ammaliare e tradire in egual misura. Tra ammutinamenti, agguati e inseguimenti, Jim dovrà crescere in fretta per sopravvivere alla caccia al tesoro più famosa della letteratura.", "https://m.media-amazon.com/images/I/61A4sugk0uL._SL1500_.jpg", "feltrinelli"));
        books.add(createDemoBook("Sotto l'aquila di Roma", "Simon Scarrow", "avventura", "Britannia, 42 d.C.: le legioni romane sbarcano per conquistare un'isola ostile e sconosciuta. Il centurione Macrone e il giovane recluta Catone si trovano fianco a fianco ad affrontare imboscate, tribù ribelli e intrighi di potere che minacciano la spedizione imperiale. Il primo capitolo di un'amicizia che diventerà leggenda, tra battaglie sanguinose e il fascino spietato della grandezza di Roma.", "https://m.media-amazon.com/images/I/51KlDiG1F1L.jpg", "newton"));
        books.add(createDemoBook("Il centurione", "Simon Scarrow", "avventura", "Nel cuore dell'impero romano, Macrone e Catone vengono inviati in missioni sempre più pericolose ai confini del mondo conosciuto. Tra tradimenti nelle fila dell'esercito e nemici che non conoscono pietà, i due soldati dovranno dimostrare che il coraggio e la lealtà contano più di qualunque strategia militare, in un racconto di guerra e amicizia che ha conquistato milioni di lettori.", "https://m.media-amazon.com/images/I/51RvBRSKiVL.jpg", "newton"));
        books.add(createDemoBook("Il gladiatore", "Simon Scarrow", "avventura", "Un complotto minaccia la stabilità di Roma e solo Macrone e Catone possono sventarlo, infiltrandosi in un mondo fatto di arene insanguinate, gladiatori spietati e nobili corrotti. Tra la polvere dei combattimenti e i sussurri di palazzo, i due eroi dovranno scoprire chi tira le fila della cospirazione prima che sia troppo tardi per salvare l'impero.", "https://m.media-amazon.com/images/I/51o7IsK5h8L.jpg", "newton"));
        books.add(createDemoBook("Q", "Luther Blissett (Wu Ming)", "avventura", "Nell'Europa sconvolta dalle guerre di religione del Cinquecento, un rivoluzionario senza nome attraversa decenni di rivolte, eresie e battaglie, sempre inseguito dall'ombra di un misterioso agente segreto del Vaticano conosciuto solo con la lettera Q. Un romanzo corale che intreccia storia e finzione in un'epopea di lotte, tradimenti e utopie infrante lungo tutto il continente.", "https://m.media-amazon.com/images/I/415MVK74HnL._SL1500_.jpg", "einaudi"));
        books.add(createDemoBook("Manituana", "Wu Ming", "avventura", "Nord America, 1775: mentre scoppia la guerra d'indipendenza americana, il popolo Mohawk guidato da Joseph Brant si trova a dover scegliere da che parte schierarsi in un conflitto che cambierà per sempre il continente. Tra foreste sconfinate, alleanze fragili e battaglie decisive, un romanzo corale che racconta la nascita di una nazione dal punto di vista di chi rischia di scomparire per sempre.", "https://m.media-amazon.com/images/I/61-AdlGcr9L._SL1291_.jpg", "einaudi"));
        books.add(createDemoBook("L'armata dei sonnambuli", "Wu Ming", "avventura", "Parigi, 1794: nel pieno del Regime del Terrore della Rivoluzione Francese, un uomo mascherato si aggira sui tetti proteggendo la plebe rivoluzionaria, mentre una forza misteriosa chiamata 'fluido' sembra manipolare i destini della città. Tra mesmerismo, complotti realisti e un'armata di sonnambuli immuni al dolore, un affresco corale e febbrile degli anni più cupi e affascinanti della storia europea.", "https://m.media-amazon.com/images/I/81AjN8woWaL._SL1500_.jpg", "einaudi"));

        // --- 6. POESIA ---
        books.add(createDemoBook("Ossi di seppia", "Eugenio Montale", "poesia", "La raccolta d'esordio del futuro Premio Nobel, pubblicata nel 1925, che ha segnato una svolta decisiva nella lirica del Novecento italiano. Tra paesaggi liguri aridi e scabri, il mare visto come elemento insieme attraente e negato, Montale costruisce una poetica degli 'scarti' e dei residui, lontana da ogni retorica, capace di restituire il senso di smarrimento e di ricerca di un'epoca intera attraverso immagini di rara essenzialità.", "https://m.media-amazon.com/images/I/61tQyhDll+L._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("Vita d'un uomo. 106 poesie 1914-1960", "Giuseppe Ungaretti", "poesia", "L'opera che raccoglie oltre quarant'anni di scrittura poetica di uno dei grandi maestri dell'Ermetismo italiano, dalle liriche brevi e folgoranti scritte nelle trincee della Prima guerra mondiale fino alle raccolte della maturità. Un percorso che attraversa dolore, guerra, fede e memoria, condensato in versi scarni e potentissimi che hanno rivoluzionato il linguaggio poetico del Novecento.", "https://m.media-amazon.com/images/I/61XUwqBV-GL._SL1035_.jpg", "mondadori"));
        books.add(createDemoBook("Testamento seguito da La Terra Santa", "Alda Merini", "poesia", "Due libri cardine della poetessa dei Navigli riuniti in un solo volume, nati dagli anni del ricovero al manicomio Paolo Pini. Versi che trasformano la sofferenza e l'internamento in una lente per guardare il mondo da un altrove, tra figure dantesche, bibliche e mitologiche che si intrecciano a un linguaggio insieme visionario e carnale, capace di restituire dignità e voce a chi era stato ridotto al silenzio.", "https://m.media-amazon.com/images/I/51hYdffOXGL._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("Poesie fuggitive", "Edoardo Sanguineti", "poesia", "Una selezione di liriche tratte da 'Il gatto lupesco', tra le opere più mature di uno dei protagonisti della Neoavanguardia italiana. Versi brevi e densi, capaci di intrecciare il quotidiano e il cosmico, l'ironia e la malinconia, in una lingua che gioca costantemente con la tradizione per romperla e reinventarla, offrendo un ritratto intimo e sorprendente di uno dei poeti più sperimentali del secondo Novecento.", "https://m.media-amazon.com/images/I/41qS9jiIj5L.jpg", "feltrinelli"));
        books.add(createDemoBook("Un quaderno di radici", "Tiziano Fratus", "poesia", "Il ritorno alla poesia del cercatore d'alberi Tiziano Fratus, in una raccolta che intreccia il lutto per le figure genitoriali scomparse con un amore profondo per gli alberi e le foreste. Tra haiku, poemetti e versi in dialetto lombardo, l'autore costruisce un erbario emotivo che parla di radici, memoria e del rapporto quotidiano tra l'uomo e la natura che lo circonda.", "https://m.media-amazon.com/images/I/41UQRaHf7KL.jpg", "feltrinelli"));
        books.add(createDemoBook("Solo andata. Righe che vanno troppo spesso a capo", "Erri De Luca", "poesia", "Un poema epico e scabro che racconta la traversata del Mediterraneo di un gruppo di migranti in fuga dall'Africa verso i porti del nord. Con un linguaggio ruvido e privo di retorica, De Luca dà voce a un viaggio senza tempo fatto di paura, pazienza e speranza, in una seconda parte più lirica e aforistica che riflette su memoria, giustizia e sopravvivenza.", "https://m.media-amazon.com/images/I/71aweMkXi5L._SL1500_.jpg", "feltrinelli"));
        books.add(createDemoBook("I Canti", "Giacomo Leopardi", "poesia", "La raccolta poetica che rappresenta una delle vette assolute della lirica italiana e mondiale, dagli idilli giovanili alle canzoni della maturità fino ai grandi canti filosofici degli ultimi anni. Attraverso il tema del dolore universale, della natura indifferente e della ricerca della felicità, Leopardi costruisce un'opera di rara profondità speculativa e insieme di straordinaria bellezza formale, capace di parlare ancora oggi a ogni lettore.", "https://m.media-amazon.com/images/I/51tpr1tjAsL._SL1000_.jpg", "newton"));
        books.add(createDemoBook("I fiori del male e tutte le poesie", "Charles Baudelaire", "poesia", "L'opera che ha rivoluzionato la poesia moderna, esplorando il conflitto tra spleen e ideale, bellezza e decadenza, attrazione per il peccato e ricerca del sublime. Lontano dalla leggenda del semplice 'cantore del male', Baudelaire rivela un percorso spirituale complesso e tormentato, capace di anticipare le inquietudini e le contraddizioni dell'uomo contemporaneo attraverso immagini di potenza visionaria.", "https://m.media-amazon.com/images/I/713+zP3c4lL._SL1500_.jpg", "newton"));
        books.add(createDemoBook("Foglie d'erba", "Walt Whitman", "poesia", "Il capolavoro del padre della poesia americana moderna, un canto continuo e in perenne espansione dedicato alla democrazia, al corpo, alla natura e all'individuo. Attraverso versi liberi e un respiro ampio e inedito per l'epoca, Whitman celebra l'uomo comune e l'esperienza sensoriale del mondo, costruendo un'opera che ha influenzato profondamente tutta la poesia successiva.", "https://m.media-amazon.com/images/I/71WGXSVcARL._SL1500_.jpg", "newton"));
        books.add(createDemoBook("Il Canzoniere", "Umberto Saba", "poesia", "L'opera che raccoglie oltre cinquant'anni di produzione lirica del poeta triestino, organizzata come un unico grande organismo narrativo diviso in giovinezza, maturità e vecchiaia. Tra il rapporto con la città natale, gli affetti familiari e il mondo animale, Saba costruisce, in equilibrio tra classicità e contemporaneità, un linguaggio poetico di rara limpidezza, lontano dalle sperimentazioni delle avanguardie coeve.", "https://m.media-amazon.com/images/I/71Y4Bgb7gyL._SL1500_.jpg", "einaudi"));
        books.add(createDemoBook("Lavorare stanca", "Cesare Pavese", "poesia", "La raccolta che rivelò Pavese poeta prima ancora che narratore, concentrando un intero universo esistenziale che ritroveremo poi nei suoi romanzi. Una Torino fatta di viali e periferie, una campagna che si trasfigura in dimensione mitica, e un progetto di poesia narrativa che racconta eroi vinti e sognanti, in versi che rompono con l'ermetismo dominante per abbracciare un respiro epico e popolare.", "https://m.media-amazon.com/images/I/810ccwACa0L._SL1500_.jpg", "einaudi"));
        books.add(createDemoBook("Vuoto d'amore", "Alda Merini", "poesia", "Una delle raccolte più intense della poetessa milanese, curata da Maria Corti, che esplora il tema della perdita e dell'assenza attraverso un linguaggio insieme fragile e potentissimo. Merini trasforma il vuoto lasciato dall'amore in uno spazio di conoscenza e resistenza, con versi che oscillano tra il grido e il canto, tra la disperazione più nuda e un'inaspettata, ostinata vitalità.", "https://m.media-amazon.com/images/I/61J0yQaW3DL._SL1072_.jpg", "einaudi"));

        // --- 7. STORICI ---
        books.add(createDemoBook("Alexandros", "Valerio Massimo Manfredi", "storici", "Nella Macedonia del IV secolo a.C., il giovane Alessandro cresce all'ombra di un padre ingombrante e di un destino già scritto nelle profezie. Allievo di Aristotele, addestrato alla guerra fin da ragazzo, sogna di unire il mondo greco e quello barbaro in un unico grande impero. Dalla congiura che uccide Filippo II fino alla conquista dell'Asia, Manfredi ricostruisce con rigore archeologico la parabola dell'uomo che si credette figlio degli dèi.", "https://m.media-amazon.com/images/I/615CVR2in0L.SL1500.jpg", "mondadori"));
        books.add(createDemoBook("L'ultima legione", "Valerio Massimo Manfredi", "storici", "Anno 476 d.C.: l'impero romano d'Occidente sta crollando sotto i colpi dei barbari, e il piccolo imperatore Romolo Augusto viene esiliato su un'isola sperduta. Un pugno di legionari fedeli, guidati dal centurione Aurelio, decide di non arrendersi e intraprende un viaggio disperato attraverso un continente in fiamme per salvare l'ultimo erede di Roma, portando con sé un segreto capace di cambiare il corso della storia.", "https://m.media-amazon.com/images/I/719HCRAxFVL.SL1500.jpg", "mondadori"));
        books.add(createDemoBook("L'armata perduta", "Valerio Massimo Manfredi", "storici", "Ispirato all'Anabasi di Senofonte, il romanzo racconta le vicende di diecimila mercenari greci che, dopo aver combattuto per un principe persiano sconfitto in battaglia, si ritrovano isolati nel cuore dell'impero nemico, a migliaia di chilometri da casa. Guidati da un manipolo di generali coraggiosi, dovranno marciare attraverso deserti, montagne e popoli ostili in un'epica ritirata verso la salvezza.", "https://m.media-amazon.com/images/I/71HdOdCWntL.SL1500.jpg", "mondadori"));
        books.add(createDemoBook("La Mennulara", "Simonetta Agnello Hornby", "storici", "Sicilia, 1963: nel paese di Roccacolomba muore Maria Rosalia Inzerillo, detta la Mennulara, per anni amministratrice fedele e temuta del patrimonio della nobile famiglia Alfallipe. Il suo testamento, tanto inatteso quanto sconvolgente, costringe gli eredi a fare i conti con segreti, rancori e ipocrisie di un mondo provinciale in cui tutti sanno tutto di tutti, ma nessuno conosce davvero la verità sulla donna che per una vita intera li ha protetti.", "https://m.media-amazon.com/images/I/51gjB+N5rrL.SL1000.jpg", "feltrinelli"));
        books.add(createDemoBook("La zia marchesa", "Simonetta Agnello Hornby", "storici", "Nella Sicilia di fine Ottocento, Costanza Safamita cresce amata dal padre barone e rifiutata dalla madre, segnata da una chioma rossa che la rende diversa agli occhi di tutti. Erede designata di un vasto patrimonio, dovrà affrontare la mondanità di Palermo, un matrimonio complicato e il potere occulto della mafia locale, in un affresco vivido di un'aristocrazia agraria condannata a scomparire.", "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRknHcc7QvLD2hNYhtRavglFM5Eqfoa3SzzrTQKmaO3dzeGQS-x", "feltrinelli"));
        books.add(createDemoBook("Boccamurata", "Simonetta Agnello Hornby", "storici", "Tra Palermo e Napoli, in un intreccio di epoche e generazioni, si dipana la storia di una famiglia segnata da silenzi, tradimenti e legami di sangue mai del tutto sciolti. Agnello Hornby racconta con la consueta sensibilità le vite di donne costrette a scegliere tra i doveri imposti dalla società e i desideri più intimi, in una Sicilia sospesa tra tradizione e cambiamento.", "https://m.media-amazon.com/images/I/91nd3jSEDWL.SL1500.jpg", "feltrinelli"));
        books.add(createDemoBook("Il mercante di libri maledetti", "Marcello Simoni", "storici", "Francia, XIII secolo: il mercante di reliquie Ignazio da Toledo si mette sulle tracce di un manoscritto leggendario, l'Uter Ventorum, capace secondo un'antica profezia di rivelare il volto del demonio. Tra abbazie fortificate, biblioteche proibite e ordini religiosi pronti a tutto pur di custodire il segreto, un romanzo che unisce rigore storico e atmosfere gotiche nel cuore del Medioevo.", "https://m.media-amazon.com/images/I/8106Aq4NbNL.SL1500.jpg", "newton"));
        books.add(createDemoBook("La biblioteca perduta dell'alchimista", "Marcello Simoni", "storici", "Sulle tracce di un'antica biblioteca alchemica scomparsa da secoli, Ignazio da Toledo si addentra in un intrigo che attraversa monasteri, corti e città portuali del Mediterraneo medievale. Tra manoscritti proibiti e società segrete, il mercante di libri dovrà affrontare nemici spietati pur di svelare un sapere che qualcuno è disposto a uccidere per proteggere.", "https://m.media-amazon.com/images/I/713sSEQCKnL.SL1499.jpg", "newton"));
        books.add(createDemoBook("L'isola dei monaci senza nome", "Marcello Simoni", "storici", "In un monastero remoto e dimenticato, un ordine di monaci privi di identità custodisce da generazioni un segreto capace di sconvolgere gli equilibri della cristianità medievale. Quando un enigmatico visitatore giunge sull'isola, antiche verità sepolte cominciano a riaffiorare, trascinando i protagonisti in un vortice di fede, potere e inganni che affonda le radici nei secoli più bui del Medioevo.", "https://m.media-amazon.com/images/I/81JLr6D+xgL.SL1500.jpg", "newton"));
        books.add(createDemoBook("La Storia", "Elsa Morante", "storici", "Roma, 1941: la maestra Ida Ramundo, vedova e mezza ebrea, viene violentata da un giovane soldato tedesco durante un rastrellamento, e da quell'incontro nascerà Useppe, bambino fragile e luminoso. Attraverso gli occhi di madre e figlio, Morante racconta gli anni della guerra e del dopoguerra italiano, in un affresco corale che intreccia la grande Storia alle vite minime e dimenticate di chi la subisce senza comprenderla.", "https://m.media-amazon.com/images/I/81kiXDJiMVL.SL1500.jpg", "einaudi"));
        books.add(createDemoBook("Q", "Luther Blissett (Wu Ming)", "storici", "Nell'Europa sconvolta dalle guerre di religione del Cinquecento, un rivoluzionario senza nome attraversa decenni di rivolte contadine, eresie messianiche e battaglie sanguinose, sempre inseguito dall'ombra di un agente segreto del Vaticano conosciuto solo con la lettera Q. Un affresco corale che intreccia storia e finzione lungo tutto il continente, tra utopie di libertà e feroci repressioni.", "https://m.media-amazon.com/images/I/415MVK74HnL.SL1500.jpg", "einaudi"));
        books.add(createDemoBook("Manituana", "Wu Ming", "storici", "Nord America, 1775: mentre scoppia la guerra d'indipendenza americana, il popolo Mohawk guidato da Joseph Brant si trova costretto a scegliere da che parte schierarsi in un conflitto che deciderà il destino di un intero continente. Tra foreste sconfinate e alleanze fragili tra coloni e nativi, un romanzo corale che racconta la nascita degli Stati Uniti dal punto di vista di chi rischiava di scomparire per sempre dalla Storia.", "https://m.media-amazon.com/images/I/61-AdlGcr9L.SL1291.jpg", "einaudi"));

        // --- 8. FILOSOFICI ---
        books.add(createDemoBook("Discorso sul metodo", "Cartesio", "filosofici", "Pubblicato nel 1637 come premessa metodologica a una serie di trattati scientifici, questo testo segna l'avvento di un modo radicalmente nuovo di concepire la conoscenza, fondato sulla razionalità dell'uomo. Attraverso una prosa lucida e quasi autobiografica, Cartesio racconta il cammino che lo ha condotto a formulare il celebre dubbio sistematico e il metodo per condurre correttamente la propria ragione, gettando le basi della filosofia e della scienza moderne.", "https://m.media-amazon.com/images/I/71vgqgI-7CL._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("Il Principe", "Niccolò Machiavelli", "filosofici", "Scritto nel 1513 in un momento di crisi politica per l'Italia, questo trattato disegna il ritratto di un uomo di Stato capace di dominare la sorte attraverso virtù e pragmatismo, separando per la prima volta con nettezza l'agire politico dalla morale tradizionale. Un'opera breve ma dirompente, che ha inaugurato il pensiero politico moderno e che continua a essere letta come chiave per comprendere i meccanismi del potere.", "https://m.media-amazon.com/images/I/71xu7odCppL._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("Confessioni", "Sant'Agostino", "filosofici", "Il racconto intimo e filosofico della conversione di uno degli spiriti più inquieti dell'antichità tardiva, che ripercorre la propria giovinezza dissoluta, la ricerca affannosa della verità tra diverse scuole di pensiero e l'incontro decisivo con la fede cristiana. Un'opera che intreccia autobiografia, teologia e riflessione filosofica sul tempo, la memoria e il male, ponendo le basi per secoli di pensiero occidentale.", "https://m.media-amazon.com/images/I/61xisA8svYL._SL1500_.jpg", "mondadori"));
        books.add(createDemoBook("La banalità del male. Eichmann a Gerusalemme", "Hannah Arendt", "filosofici", "Il resoconto del processo ad Adolf Eichmann, uno dei principali organizzatori della deportazione degli ebrei europei, diventa per Arendt l'occasione per una riflessione filosofica sconvolgente: il male estremo non nasce necessariamente da mostri, ma può annidarsi nella semplice incapacità di pensare e nell'obbedienza burocratica. Un'opera fondamentale per comprendere la natura del totalitarismo e la fragilità del giudizio morale.", "https://m.media-amazon.com/images/I/71S8lhIDS+L._SL1500_.jpg", "feltrinelli"));
        books.add(createDemoBook("L'essenza del cristianesimo", "Ludwig Feuerbach", "filosofici", "Uno dei testi cardine della critica filosofica alla religione, in cui Feuerbach sostiene che Dio non sia altro che la proiezione idealizzata delle qualità migliori dell'uomo, alienate e collocate in una dimensione trascendente. Un'opera che ha influenzato profondamente il pensiero successivo, da Marx a Nietzsche, invitando l'umanità a riappropriarsi della propria essenza invece di adorarla sotto forma divina.", "https://m.media-amazon.com/images/I/71vG5Ma5zfL._SL1500_.jpg", "feltrinelli"));
        books.add(createDemoBook("Contro il metodo", "Paul Feyerabend", "filosofici", "Un attacco radicale all'idea che la scienza proceda seguendo un metodo razionale unico e universale, sostenendo invece che il progresso scientifico sia storicamente avvenuto anche attraverso violazioni delle regole più consolidate. Feyerabend propone un 'anarchismo epistemologico' provocatorio e dissacrante, che ha scatenato accesi dibattiti sulla natura stessa della conoscenza scientifica.", "https://m.media-amazon.com/images/I/91RPFpw9hrL._SL1500_.jpg", "feltrinelli"));
        books.add(createDemoBook("Così parlò Zarathustra", "Friedrich Nietzsche", "filosofici", "Il capolavoro filosofico-poetico in cui Nietzsche affida al profeta Zarathustra la propria visione del mondo: la morte di Dio, la dottrina del superuomo e quella dell'eterno ritorno. Attraverso uno stile visionario a metà tra il poema e il trattato filosofico, l'opera invita l'umanità a superare i vecchi valori per crearne di nuovi, in una delle riflessioni più influenti e discusse della storia del pensiero occidentale.", "https://m.media-amazon.com/images/I/71U4WaJU1UL._SL1500_.jpg", "newton"));
        books.add(createDemoBook("Il mondo come volontà e rappresentazione", "Arthur Schopenhauer", "filosofici", "L'opera che rivoluziona la filosofia ottocentesca proponendo una distinzione decisiva tra il mondo come appare ai nostri sensi e la sua sostanza più profonda, una volontà cieca e insaziabile che si manifesta in ogni forma di vita. Da questa visione pessimistica dell'esistenza, Schopenhauer sviluppa una riflessione sull'arte, la compassione e l'ascesi come possibili vie di liberazione dal dolore del volere.", "https://m.media-amazon.com/images/I/715g4UxcT3L._SL1500_.jpg", "newton"));
        books.add(createDemoBook("La Repubblica", "Platone", "filosofici", "Il dialogo più celebre di Platone, in cui Socrate discute con i suoi interlocutori la natura della giustizia, delineando il progetto di una città ideale governata da filosofi illuminati. Tra il mito della caverna, la teoria delle idee e la riflessione sull'educazione dell'anima, l'opera getta le fondamenta della filosofia politica occidentale e rimane una delle indagini più profonde mai scritte sul rapporto tra conoscenza, virtù e potere.", "https://m.media-amazon.com/images/I/81BJQNUR05L._SL1500_.jpg", "newton"));
        books.add(createDemoBook("Tractatus logico-philosophicus", "Ludwig Wittgenstein", "filosofici", "L'opera che ha segnato una svolta radicale nella filosofia del linguaggio del Novecento, costruita attraverso una sequenza di proposizioni numerate che indagano il rapporto tra linguaggio, pensiero e realtà. Wittgenstein traccia i confini di ciò che può essere detto sensatamente, concludendo che su ciò di cui non si può parlare si deve tacere, in un testo denso quanto influente per tutta la filosofia analitica successiva.", "https://m.media-amazon.com/images/I/61E9MVP-H7L._SL1421_.jpg", "einaudi"));
        books.add(createDemoBook("Sorvegliare e punire. Nascita della prigione", "Michel Foucault", "filosofici", "Un'indagine storica e filosofica sulla nascita del sistema carcerario moderno, che ricostruisce il passaggio dai supplizi pubblici dell'antico regime alla disciplina invisibile e capillare delle istituzioni moderne. Foucault mostra come il potere non agisca più solo attraverso la repressione violenta, ma attraverso la sorveglianza costante e la normalizzazione dei corpi, in un'analisi che ha rivoluzionato il modo di pensare le istituzioni.", "https://m.media-amazon.com/images/I/71KEv1I4uYL._SL1184_.jpg", "einaudi"));
        books.add(createDemoBook("La struttura delle rivoluzioni scientifiche", "Thomas S. Kuhn", "filosofici", "Il saggio che ha introdotto nel dibattito filosofico ed epistemologico il concetto di 'paradigma', sostenendo che la scienza non progredisce in modo lineare e cumulativo ma attraverso rivoluzioni concettuali che rovesciano le teorie precedenti. Un'opera che ha cambiato profondamente il modo di intendere la storia della scienza, influenzando filosofia, sociologia e teoria della conoscenza ben oltre i confini della disciplina scientifica.", "https://m.media-amazon.com/images/I/61Do-eDmaxL._SL1410_.jpg", "einaudi"));

        // LIBRO VECCHIO PER IL TIMER
        Book libroVecchio = books.stream()
                .filter(b -> b.getTitle().equalsIgnoreCase("Il Signore degli Anelli"))
                .findFirst()
                .orElse(null);

        if (libroVecchio != null) {
            libroVecchio.setStatus(it.ispwproject.findyourbook.enumerator.ReadingStatus.READING);
            libroVecchio.setReadingStartDate(LocalDate.now(java.time.ZoneId.systemDefault()).minusDays(35));

            List<Book> marioLibrary = new ArrayList<>();
            marioLibrary.add(libroVecchio);

            // 2. DA LEGGERE
            Book libroDaLeggere = books.stream()
                    .filter(b -> b.getTitle().equalsIgnoreCase("Dieci piccoli indiani"))
                    .findFirst()
                    .orElse(null);

            if (libroDaLeggere != null) {
                libroDaLeggere.setStatus(it.ispwproject.findyourbook.enumerator.ReadingStatus.TO_READ);
                marioLibrary.add(libroDaLeggere);
            }

            // 3. LETTI
            String[] titoliLetti = {"Orgoglio e pregiudizio", "Moby Dick", "Le cronache di Narnia"};
            for (String titolo : titoliLetti) {
                Book libroLetto = books.stream()
                        .filter(b -> b.getTitle().equalsIgnoreCase(titolo))
                        .findFirst()
                        .orElse(null);

                if (libroLetto != null) {
                    libroLetto.setStatus(it.ispwproject.findyourbook.enumerator.ReadingStatus.READ);
                    marioLibrary.add(libroLetto);
                }
            }

            favorites.put("mario", marioLibrary);
        }
    }

    /**
     * Metodo helper per creare velocemente i libri finti per la Demo.
     * NOTA: Controlla che i nomi di questi SETTER combacino esattamente
     * con quelli che hai scritto nella tua classe "Book" (es. setTitle, setPublisherUsername ecc.)
     */
    private Book createDemoBook(String title, String author, String genre, String description, String imageUrl, String publisherUsername) {
        Book b = new Book();
        b.setId(nextBookId++);
        b.setTitle(title);
        b.setAuthor(author);
        b.setGenre(genre);
        b.setDescription(description);
        b.setImageUrl(imageUrl);
        b.setPublisherUsername(publisherUsername);

        b.setCopieVendute(RANDOM.nextInt(1000));
        return b;
    }

    public List<User> getUsers() { return users; }
    public List<Book> getBooks() { return books; }
    public Map<String, List<Book>> getFavorites() { return favorites; }

    public int nextUserId() { return nextUserId++; }
    public int nextBookId() { return nextBookId++; }

}